[package]
authors = ["Meng Wang <mengwanguc@gmail.com>"]
build = "build.rs"
name = "rust-mio"
version = "0.2.0"
description = "Rust API of Cortx motr ---- a trial"
license = "MIT OR Apache-2.0"

[dependencies]
anyhow = "1.0.23"

[build-dependencies]
bindgen = "0.59.1"
run_script = "0.6.3"
